# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform Principal Component Analysis (PCA) on a dataset.
#' 
#' This function takes a numeric matrix as input and performs PCA on the dataset.
#' The function allows the user to specify the number of principal components to retain
#' or the percentage of variance to be explained by the retained components.
#' 
#' @param data A numeric matrix containing the input data.
#' @param num_components The number of principal components to retain (default: -1).
#'                       If set to -1, all components will be retained.
#' @param variance_percentage The percentage of variance to be explained by the retained components (default: -1).
#'                            If set to -1, all components will be retained.
#' @return A numeric matrix containing the projected data in the principal component space.
#'
armaPCA <- function(data, num_components = -1L, variance_percentage = -1) {
    .Call(`_dimensionreduction_armaPCA`, data, num_components, variance_percentage)
}

#' This function implements the Linear Discriminant Analysis (LDA) algorithm to reduce the dimensionality of data to the specified number of components.
#' The input parameters include the data matrix X, the class label vector y, and the number of components num_components.
#'
#'@param X Data matrix, where each row represents a sample and each column represents a feature.
#' @param y Class label vector indicating the class membership of each sample.
#' @param num_components Number of dimensions for LDA dimensionality reduction.
#'
#' @return The reduced-dimensional data matrix, where each row represents a sample and each column represents a reduced feature.
#'
armalda <- function(X, y, num_components) {
    .Call(`_dimensionreduction_armalda`, X, y, num_components)
}

#' R 包接口函数
#' This function serves as the interface between R and the t-SNE algorithm implemented in C++.
#' It takes the input data matrix, along with optional parameters, and returns the t-SNE embedding.
#' @param data Data matrix, where each row represents a sample and each column represents a feature.
#' @param num_dims Number of dimensions for the t-SNE embedding(default: 2).
#' @param num_iters Number of iterations for the t-SNE algorithm(default: 1000).
#' @param learning_rate Learning rate for the t-SNE algorithm(default: 200.0).
#' @param perplexity Perplexity parameter for the t-SNE algorithm(default: 30.0).
#'
#' @return The t-SNE embedding as a numeric matrix, where each row represents a sample and each column represents a reduced feature.
armaTsne <- function(data, num_dims = 2L, num_iters = 1000L, learning_rate = 200.0, perplexity = 30.0) {
    .Call(`_dimensionreduction_armaTsne`, data, num_dims, num_iters, learning_rate, perplexity)
}

#' Function to compute the Locally Linear Embedding (LLE) algorithm
#' This function takes the input data matrix, along with the parameters k and d, and returns the LLE embedding.
#'
#' @param data Data matrix, where each row represents a sample and each column represents a feature.
#' @param k Number of nearest neighbors to consider for each sample.
#' @param d Number of dimensions for the LLE embedding.
#'
#' @return The LLE embedding as a numeric matrix, where each row represents a sample and each column represents a reduced feature.
armalle <- function(data, k, d) {
    .Call(`_dimensionreduction_armalle`, data, k, d)
}

